### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tsargent** [HipsterBrown/espresso#12]
not sure if I'm doing something wrong here.  Given I'm in a directory `events/` of coffeescript files:

``` bash
$ espresso
module.js:339
    throw err;
    ^

Error: Cannot find module '../dist/index.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/tylersargent/.nvm/versions/node/v5.0.0/lib/node_modules/espresso-transformer/bin/espresso.sh:9:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)

```

**Comment by HipsterBrown** [comment]
Fixed by removing `dist/` pre-publish hooks and `babel` compilation.
